name: Publish Docker image

on:
  push:
    branches:
      - main

env:
  hash: $(git rev-parse --short=8 "$GITHUB_SHA")

jobs:

  push:

    name: Build and Push ${{ matrix.image }} for ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
          - platform: arm64
            # runner: ubuntu-24.04-arm # Uncomment when arm64 runners are available on GitHub Actions
            runner: ubuntu-24.04
        image:
          - php8.2-cli-alpine
          - php8.2-nginx-alpine

    steps:

      - uses: actions/checkout@v4

      - name: Set globals
        id: globals
        shell: bash
        run: |
          echo "HASH=${{ env.hash }}" >> "${GITHUB_OUTPUT}"
          echo "IMAGE_NAME=metarisc:${{ matrix.image }}" >> "${GITHUB_OUTPUT}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for cross-platform builds
        if: matrix.platform == 'arm64'
        uses: docker/setup-qemu-action@v3

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}
          username: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/${{ matrix.platform }}
          tags: |
              ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/${{ steps.globals.outputs.IMAGE_NAME }}-latest
              ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/${{ steps.globals.outputs.IMAGE_NAME }}-${{ steps.globals.outputs.HASH }}
          context: ${{ matrix.image }}
          cache-from: type=gha,ref=${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/${{ steps.globals.outputs.IMAGE_NAME }}-${{ matrix.platform }}
          cache-to: type=gha,ref=${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/${{ steps.globals.outputs.IMAGE_NAME }}-${{ matrix.platform }},mode=max