name: Publish Docker image
  
on:
  push:
    branches:
      - main

jobs:

  push:
    
    name: Build ${{ matrix.image }} for ${{ matrix.platform }}
    runs-on: ${{ matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        image: [php8.2-cli-alpine, php8.2-nginx-alpine]

    steps:

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}
          username: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/${{ matrix.platform }}
          tags: |
            ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/metarisc:${{ matrix.image }}-${{ matrix.platform }}-latest
            ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/metarisc:${{ matrix.image }}-${{ matrix.platform }}-${{ github.sha }}
          context: ${{ matrix.image }}
          cache-from: type=gha,ref=${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/metarisc:${{ matrix.image }}-${{ matrix.platform }}
          cache-to: type=gha,ref=${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/metarisc:${{ matrix.image }}-${{ matrix.platform }},mode=max

  manifest:

    name: Create and push multi-arch manifest
    runs-on: ubuntu-latest
    needs: push
    strategy:
      matrix:
        image: [php8.2-cli-alpine, php8.2-nginx-alpine]

    steps:
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}
          username: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.SCALEWAY_DOCKER_REGISTRY_PASSWORD }}

      - name: Create and push manifest (latest and hash)
        shell: bash
        run: |
          for TAG in latest ${{ github.sha }}; do
            docker buildx imagetools create \
              --tag ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/metarisc:${{ matrix.image }}-${TAG} \
              ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/metarisc:${{ matrix.image }}-amd64-${TAG} \
              ${{ secrets.SCALEWAY_DOCKER_REGISTRY_NAMESPACE }}/metarisc:${{ matrix.image }}-arm64-${TAG}
          done